name: Update Holidays


on:
  schedule:
   - cron: '0 0 1 * *'
  push:
    branches:
      - master
      
jobs:
  update_holiday:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
        
    - name: Install Quarto CLI
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: LATEST

    - name: Install R packages And Update holiday_zh
      run: |
        Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
        Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"
        Rscript -e "source('./R/update_holiday.R')"

    - name: Rerender Quarto file
      run: |
        quarto render README.qmd

    - name: Commit holiday_zh data file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update holiday_zh"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   