name: Update Holidays

on:
  push:
    branches:
      - main

jobs:
  update-holidays:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run update_holiday.R
        run: Rscript update_holiday.R